name: Haskell CI

on: push

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    container: koellewe/haskell-stack:2.7.1

    steps:
    - run: "chown -R $(id -un):$(id -gn) ~"
    
    - name: Build
      run: stack --allow-different-user build

    - name: Run tests
      run: stack --allow-different-user test
