name: Haskell CI

on: push

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    container: koellewe/haskell-stack:2.7.1

    steps:
    - name: Build
      run: stack build
    - name: Run tests
      run: stack test
